["com.thoth.one-dark-pro"]
id = "com.thoth.one-dark-pro"
name = "One Dark Pro"
version = "1.0.2"
author = "Anit Nilay"
description = "One Dark pro theme for Thoth"
download_url = "https://github.com/anitnilay20/Thoth-plugins/releases/download/one-dark-pro-v1.0.2/one-dark-pro.zip"
sha256 = "efb362bce163babab83d96ea3d4b41ea6f3fafae5fef246599b27c3ae23f7670"
icon_url = "https://raw.githubusercontent.com/anitnilay20/Thoth-plugins/one-dark-pro/one-dark-pro/icon.png"
repo_url = "https://github.com/anitnilay20/Thoth-plugins/tree/one-dark-pro/one-dark-pro"
readme = "https://raw.githubusercontent.com/anitnilay20/Thoth-plugins/one-dark-pro/one-dark-pro/README.md"
categories = ["Theme"]