["com.thoth.one-dark-pro"]
id = "com.thoth.one-dark-pro"
name = "One Dark Pro"
version = "1.0.1"
author = "Anit Nilay"
description = "One Dark pro theme for Thoth"
download_url = "https://github.com/anitnilay20/Thoth-plugins/releases/download/one-dark-pro-v1.0.0/one-dark-pro.zip"
sha256 = "f5a51ac1ae28646fa7427afbe7aa3e9d3b11de90c439b0ea3572f6fdee455deb"
icon_url = "https://raw.githubusercontent.com/anitnilay20/Thoth-plugins/one-dark-pro/one-dark-pro/icon.png"
repo_url = "https://github.com/anitnilay20/Thoth-plugins/tree/one-dark-pro/one-dark-pro"
readme = "https://raw.githubusercontent.com/anitnilay20/Thoth-plugins/one-dark-pro/one-dark-pro/README.md"